### ISSUE TITLE
UnhandledPromiseRejection on several sizes

### ISSUE THREAD

**Issue by pearnaly** [github1/svg-to-png-loader#7]
Hello @github1, thank you for your loader. I am experiencing the following issue with it:
```
// file src/polyfills-chromium.ts
  require("svg-to-png-loader?" +
    //"sizes[]=16," +
    //"sizes[]=24," +
    //"sizes[]=32," +
    //"sizes[]=48," +
    "sizes[]=128" +
    "&name=icons/[name]-[height]x[width].png!./icons/icon.svg");
```
(first with only one size). This will work (generate dist/icons/icon-128*128.png), but this will also unexpectedly copy the source (src/icons/icon.svg) to dist/icon.svg and also generate an empty "icons" folder outside of dist (next to it)!

Worst, if I activate several sizes, I will get the following error. Not systematically, but the more sizes I activate, the more probable it will be (concurrency problem?):

```
/ Generating browser application bundles (phase: building)...(node:12120) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\ExecutionContext.js:167:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ExecutionContext._evaluateInternal (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\ExecutionContext.js:120:56)
    at ExecutionContext.evaluate (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
    at Converter.[setDimensions] (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:348:5)
    at Converter.[convert] (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:207:5)
    at Converter.convertFile (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:148:20)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\Page.js:833:43)
    at Page.<anonymous> (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\helper.js:112:23)
    at Converter.[setDimensions] (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:348:16)
    at Converter.[convert] (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:207:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Converter.convertFile (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:148:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on
 unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12120) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\ExecutionContext.js:167:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ExecutionContext._evaluateInternal (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\ExecutionContext.js:120:56)
    at ExecutionContext.evaluate (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
    at Converter.[setDimensions] (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:348:5)
    at Converter.[convert] (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:207:5)
    at Converter.convertFile (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:148:20)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\Page.js:833:43)
    at Page.<anonymous> (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\puppeteer\lib\helper.js:112:23)
    at Converter.[setDimensions] (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:348:16)
    at Converter.[convert] (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:207:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Converter.convertFile (C:\Users\pearn\Workplace\javascript-css-injetor\node_modules\convert-svg-core\src\Converter.js:148:20)
(node:12120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on
 unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

I run Windows 10, Node 14.16.0, NPM 6.14.11, TypeScript 4.1.5
Thank you!

**Comment by github1** [comment]
Hi @pearnaly - so it appears I'm able to reproduce the UnhandledPromiseRejectionWarning using Node 14.16.0. I suspect this is ultimately an issue with convert-svg-to-png and or puppeteer but will see if there is anything I can do in this package to fix it.

**Comment by github1** [comment]
@pearnaly - can you try https://www.npmjs.com/package/svg-to-png-loader/v/4.0.0? I've change this to use [sharp](https://github.com/lovell/sharp) for svg -> png conversion.

**Comment by pearnaly** [comment]
Hi @github1, yes it worked! Thank you for your quick fix!
